### ISSUE TITLE
Further development

### ISSUE THREAD

**Issue by cyrixsimon** [GrantStreetGroup/go-exasol-client#1]
Hi, 
do you still support this project? Are you planning to do further development in order to implement the open to-dos?

**Comment by peterkioko** [comment]
Hi Simon,

Improvements to the go-exasol-client project are currently driven by our internal needs.
So, although we plan on releasing an update in the next few months, realistically speaking it is unlikely we will be addressing those open to-dos any sooner than the next 6-12 months.

However I encourage you to submit pull requests or fork the project and use it as a basis for a better client.

Regards,
Peter

**Comment by cyrixsimon** [comment]
Hi Peter,

sounds good for me - so I will submit some pull requests in the future, in order to help to make a better exasol client. 

Regards,
Simon
