### ISSUE TITLE
Replace go-logging

### ISSUE THREAD

**Issue by abergmeier** [GrantStreetGroup/go-exasol-client#3]
Looking into go-logging its' state seems to me:
- No new code since 2016
- Many unresolved Issues
- PullRequests without any comment

As a result, it seems like this module is abandoned. Thus I propose to remove/replace it.
So either use a new module or copy the necessary parts into go-exasol-client and maintain it.

**Comment by cyrixsimon** [comment]
I agree with you to replace the go-logging module. 

Maybe github.com/sirupsen/logrus may be a good choice. It is widely used and allows modern logging like structured logs. 

Another possibility would be to allow to define a logging library on initialization of go-exasol-client, which satisfy the go logging interface. This would make the logging part completely customizable.

**Comment by peterkioko** [comment]
Hi Folks,

We've just pushed out a bunch of updates and one of them removes go-logging as a dependency and replaces it with an optional Logger field in the connection configuration.  That allows you to pass in your own preferred logger as long as it conforms to the interface specified in https://github.com/GrantStreetGroup/go-exasol-client/blob/master/log.go

The tests verify that it works with logrus.  If you don't specify a Logger it uses Go's native log.

Peter
