### ISSUE TITLE
How to set handshake timeout during connect?

### ISSUE THREAD

**Issue by zlietapki** [GrantStreetGroup/go-exasol-client#6]
I didn't find any param to set connection handshake timeout

**Comment by peterkioko** [comment]
Good point.  Currently we handle the connection/handshake timeout outside of the call to connect but it does make more sense to handle it within the driver.  I'll add a param for that.

**Comment by zlietapki** [comment]
> Good point. Currently we handle the connection/handshake timeout outside of the call to connect but it does make more sense to handle it within the driver. I'll add a param for that.

Sounds great! I've made MR for that. Hope you find it useful

`From eda791fa85dbd9f9be4d259261853f01a5b33724 Mon Sep 17 00:00:00 2001
From: Andrey Martemyanov <andrey.zloy@gmail.com>
Date: Mon, 3 May 2021 21:09:51 +0300
Subject: [PATCH] handshake timeout added

---
 client.go | 9 +++++++--
 1 file changed, 7 insertions(+), 2 deletions(-)

diff --git a/client.go b/client.go
index 13a9d1c..1c2bac6 100644
--- a/client.go
+++ b/client.go
@@ -33,6 +33,7 @@ import (
 	"runtime"
 	"strconv"
 	"sync"
+	"time"
 
 	"github.com/gorilla/websocket"
 )
@@ -52,8 +53,9 @@ type ConnConf struct {
 	Timeout       uint32 // In Seconds
 	SuppressError bool   // Server errors are logged to Error by default
 	// TODO try compressionEnabled: true
-	Logger         Logger // Optional for better control over logging
-	CachePrepStmts bool
+	Logger           Logger // Optional for better control over logging
+	CachePrepStmts   bool
+	HandshakeTimeout time.Duration
 }
 
 type Conn struct {
@@ -80,6 +82,9 @@ func Connect(conf ConnConf) (*Conn, error) {
 		c.log = newDefaultLogger()
 	}
 
+	if c.Conf.HandshakeTimeout != time.Duration(0) {
+		defaultDialer.HandshakeTimeout = c.Conf.HandshakeTimeout
+	}
 	err := c.wsConnect()
 	if err != nil {
 		return nil, c.error("Unable to connect to Exasol: %s", err)
-- 
2.25.1
`

**Comment by peterkioko** [comment]
Hi Andrey - In the latest merge there are now 2 new conf options: ConnectTimeout and QueryTimeout.  QueryTimeout replaces the original "Timeout" option (which is now deprecated).
