### ISSUE TITLE
Allow caching

### ISSUE THREAD

**Issue by abergmeier** [GrantStreetGroup/go-exasol-client#8]
We have certain use cases, where we want to cache communication (readonly) with Exasol.
Now for us the easiest and most transparent would be to cache directly using the client.

Currently we are testing an initial implementation in https://github.com/abergmeier/go-exasol-client/commit/1bb220807540cd9af23e76d5aa75c475645a18b4.
The gist is that we extracted an interface for Websocket use and allow implementations to be passed into the client.
Thus we implement all caching in the Websocket handling and the client is mostly unaware.

Is there any better/easier approach to enable caching?

**Comment by peterkioko** [comment]
Hi Andreas - I think it would be fine to implement it this way, however I'm curious about the use case. What communication are trying cache? Is it different from using Exasol's built-in query cache?

**Comment by abergmeier** [comment]
> What communication are you trying cache?

Well maybe cache is the wrong word. We have multiple use cases (VPN, database upgrade) where we have no access to Exasol for a certain time.
We still want the software to be able to work though - as long as there are no mutating operations taking place.
So we store certain Websocket communication pairs and once Exasol is not reachable play back the latest stored responses.

**Comment by peterkioko** [comment]
That's an interesting use case! 
I guess it could also be used to emulate Exasol for testing purposes or to use a different websocket library if desired.
ok - I think that's worth supporting ... I'll open a ticket to add it.

**Comment by peterkioko** [comment]
I've merged some commits that include a change to allow you to specify a custom websocket layer handler. So now you can specify a [WSHandler config](https://github.com/GrantStreetGroup/go-exasol-client/blob/296e16acd5593dbf746e91a935c0a57d3388a7ae/client.go#L58) (that implements a similarly named interface).
